import Navbar from '@/Shared/Navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/Shared/Footer'
import HeadlineNav from '@/Shared/headlineNav/HeadlineNav'
import Providers from '@/provider'
import Toaster from '@/components/Toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html data-theme="cupcake" lang = "en"  > 
      <body className = {inter.className}>
      <Providers>
      
       <div className="flex min-h-screen flex-col justify-between">
            <div>
              <HeadlineNav></HeadlineNav>
              <Navbar />
              <main className="">{children}</main>
            </div>
            <Footer />
          </div>
     </Providers>
    <Toaster />
      </body>
    </html>
  )
}
